-- Run this once in Supabase SQL editor.
-- Stores daily feedback for gift + song flow.

create table if not exists public.daily_feedback (
  id bigint generated by default as identity primary key,
  day_key text not null,
  category text not null,
  feedback_text text not null,
  one_word_about_me text,
  one_word_for_me text,
  meta jsonb,
  created_at timestamptz not null default now()
);

alter table public.daily_feedback enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'daily_feedback'
      and policyname = 'Allow anonymous inserts for daily feedback'
  ) then
    create policy "Allow anonymous inserts for daily feedback"
      on public.daily_feedback
      for insert
      to anon
      with check (true);
  end if;
end $$;
